### ISSUE TITLE
Pyrotorque

### ISSUE THREAD

**Issue by TMD20** [kannibalox/pyrosimple#18]
It seems some changes have been made to pyrotorque and are not documented yet
1. The handler is now handler = "pyrocore.job.queue:QueueManager" not handler = "pyrocore.torrent.watch:QueueManager"
2. I had startable but the syntax seems to be matcher now
3. I had to comment out this line
`        # if not self.__handler and parsed_url.scheme in ("http", "https"):
        #     self.__handler = "/RPC2"
        #     self.__url += "/RPC2"`

I a little confused about what is going on print out the variables gets media, media 
media is the name of my connection. 
Anyways my path is not /rpc2 so the command was failing for me

edit: I figure it out it was the way I was trying to debug. 
It's called more then once, and I was quitting on the first run, When handler is not set. 

Q:  I got it working now, but is their any way to disable the path /rpc2?

**Comment by kannibalox** [comment]
I've added the ability to continue using `startable` if you want, but updated the documentation to match (though it still needs more work in general). The `matcher` name was chosen so that it could be re-used across multiple types of jobs.

Magically adding `/RPC2` was an attempt to be more user friendly, you can override it by making sure the URL at least has a `/` on the end, e.g. `https://example.com/` instead of `https://example.com`. I may end up removing that feature for the sake of least surprise.
