### ISSUE TITLE
Checking hash when announce URL is missing

### ISSUE THREAD

**Issue by youk** [kannibalox/pyrosimple#58]
Hash checking has nothing to do with announce URL. Thus `lstor -c` should not terminate or print error messages if announce URL is not present in metafile.

#### Current behavior:
- `lstor -c` – prints "ValueError: bad announce URL - not a string" and terminates with exit code `1`
- `lstor -V -c` – does the check and prints progress. Then prints "KeyError: 'announce'" and terminates with exit code `1`

#### Expected behavior:
At least `lstor -V -c` should not print error messages and should exit with `0` in case hash check succeeded. As for `lstor -c`, IMO it should not print error about missing URL as well (although you might have different opinion). In any case, it should not terminate with `1`, since the use case is hash checking, which succeeds.

**Comment by kannibalox** [comment]
Hm, the typical behavior of `-V` has meant "don't check the validity, but still try and display it anyway", since there are validation checks that can fail on technically displayable info. I'll probably change it to merely emit a message with the exception and continue on. Also, fair warning, I'm probably also going to change a display failure and a hash check failure to have different return codes.

**Comment by kannibalox** [comment]
`lstor -o "" -V -c <path> <file>` should now work as expected, I'll continue the general discussion in https://github.com/kannibalox/pyrosimple/issues/51

**Comment by kannibalox** [comment]
> Does this mean you find the current behavior reasonable/as designed?

Nope, it was a bug in the refactoring, now `-V` should still display the error (so you personally may still want to suppress it with `-o ""`), but it won't halt processing and won't cause lstor to return something non-zero. `-V` will still be required, as in addition to preferring to fail safe, I don't want to make people have to run lstor twice or add a special `--hash-check-but-also-validate` flag if they do end up wanting to do both. Having a flag to disable the safety checks for power users such as yourself seems reasonable.

**Comment by kannibalox** [comment]
So I went to go do a naive conversion of `hashcheck` for you, and it turns out it does the does the [exact same safety check](https://github.com/pyroscope/pyrocore/blob/master/src/pyrocore/scripts/hashcheck.py#L59-L63), but without a way to override it. Given that, I'm just going to keep things as they are.

**Comment by kannibalox** [comment]
As a general philosophy, I'm not planning to make changes that greatly decreases "safety" by default without a major version change that highlights it explicitly. While I did make a number of breaking changes during the rewrite, I'm hoping to avoid having to do that again for as long as possible.

I do agree that it shouldn't be unconditional, which is why `-V` allows skipping it.

You make a fair point about the announce URL, but I'll discuss that in the issue explicitly created for it.
