### ISSUE TITLE
last_xfer

### ISSUE THREAD

**Issue by TMD20** [kannibalox/pyrosimple#7]
Is their a replacement for last_xfer or will this feature not be included in this script?

**Comment by kannibalox** [comment]
I think I was waiting to see if there was a better way to handle `last_xfer` and `active` in cases where `timestamps.rc` wasn't set up, but since I don't have any great ideas at the moment, I've just added them back in: https://github.com/kannibalox/pyrosimple/commit/24958af9835ef607fbb7bfb984f944b3d3ec7fb3

Thanks for reporting all these by the way, I'll take some time to set up more comprehensive testing for fields
